// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package openrtb

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *SupplyChain) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Complete, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Complete")
				return
			}
		case "n":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
			if cap(z.Nodes) >= int(zb0002) {
				z.Nodes = (z.Nodes)[:zb0002]
			} else {
				z.Nodes = make([]*SupplyChainNode, zb0002)
			}
			for za0001 := range z.Nodes {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Nodes", za0001)
						return
					}
					z.Nodes[za0001] = nil
				} else {
					if z.Nodes[za0001] == nil {
						z.Nodes[za0001] = new(SupplyChainNode)
					}
					err = z.Nodes[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Nodes", za0001)
						return
					}
				}
			}
		case "v":
			z.Ver, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Ver")
				return
			}
		case "x":
			err = z.Ext.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Ext")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SupplyChain) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "c"
	err = en.Append(0x84, 0xa1, 0x63)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Complete)
	if err != nil {
		err = msgp.WrapError(err, "Complete")
		return
	}
	// write "n"
	err = en.Append(0xa1, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Nodes)))
	if err != nil {
		err = msgp.WrapError(err, "Nodes")
		return
	}
	for za0001 := range z.Nodes {
		if z.Nodes[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Nodes[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Nodes", za0001)
				return
			}
		}
	}
	// write "v"
	err = en.Append(0xa1, 0x76)
	if err != nil {
		return
	}
	err = en.WriteString(z.Ver)
	if err != nil {
		err = msgp.WrapError(err, "Ver")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = z.Ext.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Ext")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SupplyChain) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "c"
	o = append(o, 0x84, 0xa1, 0x63)
	o = msgp.AppendInt(o, z.Complete)
	// string "n"
	o = append(o, 0xa1, 0x6e)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Nodes)))
	for za0001 := range z.Nodes {
		if z.Nodes[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Nodes[za0001].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Nodes", za0001)
				return
			}
		}
	}
	// string "v"
	o = append(o, 0xa1, 0x76)
	o = msgp.AppendString(o, z.Ver)
	// string "x"
	o = append(o, 0xa1, 0x78)
	o, err = z.Ext.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Ext")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SupplyChain) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Complete, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Complete")
				return
			}
		case "n":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
			if cap(z.Nodes) >= int(zb0002) {
				z.Nodes = (z.Nodes)[:zb0002]
			} else {
				z.Nodes = make([]*SupplyChainNode, zb0002)
			}
			for za0001 := range z.Nodes {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Nodes[za0001] = nil
				} else {
					if z.Nodes[za0001] == nil {
						z.Nodes[za0001] = new(SupplyChainNode)
					}
					bts, err = z.Nodes[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nodes", za0001)
						return
					}
				}
			}
		case "v":
			z.Ver, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ver")
				return
			}
		case "x":
			bts, err = z.Ext.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ext")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SupplyChain) Msgsize() (s int) {
	s = 1 + 2 + msgp.IntSize + 2 + msgp.ArrayHeaderSize
	for za0001 := range z.Nodes {
		if z.Nodes[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Nodes[za0001].Msgsize()
		}
	}
	s += 2 + msgp.StringPrefixSize + len(z.Ver) + 2 + z.Ext.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SupplyChainNode) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a":
			z.Asi, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Asi")
				return
			}
		case "s":
			z.Sid, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Sid")
				return
			}
		case "r":
			z.Rid, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Rid")
				return
			}
		case "n":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "d":
			z.Domain, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Domain")
				return
			}
		case "h":
			z.Hp, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Hp")
				return
			}
		case "x":
			err = z.Ext.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Ext")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SupplyChainNode) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "a"
	err = en.Append(0x87, 0xa1, 0x61)
	if err != nil {
		return
	}
	err = en.WriteString(z.Asi)
	if err != nil {
		err = msgp.WrapError(err, "Asi")
		return
	}
	// write "s"
	err = en.Append(0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Sid)
	if err != nil {
		err = msgp.WrapError(err, "Sid")
		return
	}
	// write "r"
	err = en.Append(0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Rid)
	if err != nil {
		err = msgp.WrapError(err, "Rid")
		return
	}
	// write "n"
	err = en.Append(0xa1, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "d"
	err = en.Append(0xa1, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Domain)
	if err != nil {
		err = msgp.WrapError(err, "Domain")
		return
	}
	// write "h"
	err = en.Append(0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Hp)
	if err != nil {
		err = msgp.WrapError(err, "Hp")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = z.Ext.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Ext")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SupplyChainNode) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "a"
	o = append(o, 0x87, 0xa1, 0x61)
	o = msgp.AppendString(o, z.Asi)
	// string "s"
	o = append(o, 0xa1, 0x73)
	o = msgp.AppendString(o, z.Sid)
	// string "r"
	o = append(o, 0xa1, 0x72)
	o = msgp.AppendString(o, z.Rid)
	// string "n"
	o = append(o, 0xa1, 0x6e)
	o = msgp.AppendString(o, z.Name)
	// string "d"
	o = append(o, 0xa1, 0x64)
	o = msgp.AppendString(o, z.Domain)
	// string "h"
	o = append(o, 0xa1, 0x68)
	o = msgp.AppendInt(o, z.Hp)
	// string "x"
	o = append(o, 0xa1, 0x78)
	o, err = z.Ext.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Ext")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SupplyChainNode) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a":
			z.Asi, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Asi")
				return
			}
		case "s":
			z.Sid, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sid")
				return
			}
		case "r":
			z.Rid, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rid")
				return
			}
		case "n":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "d":
			z.Domain, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Domain")
				return
			}
		case "h":
			z.Hp, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Hp")
				return
			}
		case "x":
			bts, err = z.Ext.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ext")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SupplyChainNode) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Asi) + 2 + msgp.StringPrefixSize + len(z.Sid) + 2 + msgp.StringPrefixSize + len(z.Rid) + 2 + msgp.StringPrefixSize + len(z.Name) + 2 + msgp.StringPrefixSize + len(z.Domain) + 2 + msgp.IntSize + 2 + z.Ext.Msgsize()
	return
}
